# Generated by Django 3.2.5 on 2021-07-24 00:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_account', '0006_logologin'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='logologin',
            options={'ordering': ['-created'], 'verbose_name': 'عکس صفحه ورود و ثبت نام', 'verbose_name_plural': 'عکس های صفحه ورود و ثبت نام'},
        ),
    ]
