# Generated by Django 3.2.5 on 2021-07-17 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_account', '0003_alter_user_facebook_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='instagram_link',
            field=models.URLField(blank=True, max_length=150, null=True, unique=True, verbose_name='لینک اینستاگرام'),
        ),
        migrations.AlterField(
            model_name='user',
            name='pinterest_link',
            field=models.URLField(blank=True, max_length=150, null=True, unique=True, verbose_name='لینک پینترست'),
        ),
        migrations.AlterField(
            model_name='user',
            name='tweeter_link',
            field=models.URLField(blank=True, max_length=150, null=True, unique=True, verbose_name='لینک توییتر'),
        ),
        migrations.AlterField(
            model_name='user',
            name='website_link',
            field=models.URLField(blank=True, max_length=150, null=True, verbose_name='لینک وبسایت'),
        ),
        migrations.AlterField(
            model_name='user',
            name='youtube_link',
            field=models.URLField(blank=True, max_length=150, null=True, unique=True, verbose_name='لینک یوتیوب'),
        ),
    ]
