# Generated by Django 3.2.5 on 2021-07-24 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_account', '0005_auto_20210722_1759'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogoLogin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='عنوان')),
                ('logopic', models.ImageField(upload_to='blog-images', verbose_name='تصویر')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='ساخته شده')),
                ('is_active', models.BooleanField(default=False, verbose_name='فعال / غیر فعال')),
            ],
        ),
    ]
