# Generated by Django 3.2.5 on 2021-07-29 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_account', '0009_auto_20210730_0025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='bio',
            field=models.TextField(blank=True, null=True, verbose_name='توضیحات'),
        ),
    ]
