name: WaiterNews Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Make envfile
      uses: SpicyPizza/create-envfile@v1
      with:
        DB_NAME: 'waiternews'
        DB_USER: 'admin'
        DB_PASS: ${{ secrets.DB_PASSWORD }}
        SECRET_KEY: ${{ secrets.SECRET_KEY }}
        ALLOWED_HOSTS: 127.0.0.1
        file_name: .env
    - name: Build the Docker compose
      run: docker-compose -f docker-compose-deploy.yml build
    - name: Run Docker compose
      run: docker-compose -f docker-compose-deploy.yml up
    
